version: '3.8'

services:
  flask_exporter:
    build: .
    ports:
      - "21121:21121"
    env_file:
      - .env
    volumes:
      # Mount private and public keys (adjust paths as needed)
      - ./private-key.asc:/app/private-key.asc:ro
      - ./ridersguild.asc:/app/ridersguild.asc:ro
    restart: unless-stopped
