version: '3.8'

services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "21121:21121"
    env_file:
      - .env
    volumes:
      - .:/app  # Maps the current directory to the /app directory in the container
    restart: always  # Restarts the container automatically if it stops
    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge
